PerfumeProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('perfume_app.urls')),
    path('dbman/', include('perfume_db_manager.urls')),
    
]

perfume_app/urls.py
from django.urls import path

from . import views

app_name = 'perfume_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('perfumes_list/',views.perfumes_list,name='perfumes_list'),
    path('perfume/<int:pk>',views.perfume_detail,name='perfume_detail'),

 ]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/base.css'%}">
    {% block head_style %}
    {% endblock %}

    <title>Perfume</title>
</head>
<body>
     <header>
      <h1>
        <img src="{% static 'images/hplogo.png' %}" alt="logo" width="70">
      </h1>
      <form method="get" action="{% url 'perfume_app:perfumes_list' %}" id="searchForm1">
          <input type="search" name="q" class="search-input" placeholder="Search for brand,name and notes" autocomplete="off" />
      </form>
        <nav>
          <ul class="nav-menu">
            <li>
                <a href="{% url 'perfume_app:index'%}">
                    <i class="nav-icon fas fa-home"></i> Home
                </a>
            </li>
            <li>
                <a href="{% url 'perfume_app:perfumes_list'%}">
                    <i class="fa-solid fa-bottle-droplet"></i>Perfume
                </a>
            </li>
            <li>
                <a href="#">
                    <i class="fa-solid fa-right-to-bracket"></i>Login
                </a>
            </li>

          </ul>
        </nav>
    </header>
        {% block body_content %}
        {% endblock %}
    <footer>
      <div class="sns-icons">
         <a href="#"><img src="{% static 'images/twitter.png' %}" alt="twitter" width="32"></a>
        <a href="#"><img src="{% static 'images/facebook.png' %}" alt="facebook" width="32"></a>
        <a href="#"><img src="{% static 'images/instagram.png' %}" alt="instagram" width="32"></a>
      </div>
      <p><small>Copyright &copy; 2025 Erb Perfume Ltd. All Rights Reserved.</small></p>
    </footer>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
     <script src="{% static 'js/base.js'%}"></script>
     {% block body_script %}
     {% endblock %}
</body>
</html>